### ISSUE TITLE
Does not load in VCV Rack 0.6.0

### ISSUE THREAD

**Issue by DaveCasey** [bafonso/Erratic#3]
(I tried building it myself for 0.6.0 but ran into a lot of "src/MidiIO.hpp:175:2: error: reference to 'MidiIO' is ambiguous" errors.)

Is this something you have bandwidth for in the near future, or should I downgrade VCV Rack and all other plugins for now? (Linnstrument is my primary use case, so no pressure :-) )

**Comment by bafonso** [comment]
Hey Dave, I have the single voice running on 0.6 and will do the other one in the next days now that 0.6 is out :)

**Comment by bafonso** [comment]
There's a new 0.6.0 release with linux and OSX binaries. Let me know if issues you may have

**Comment by DCSIProductions** [comment]
Hi, I tried to compile from source on Windows but it gives errors: here's the result below if it may be useful. Hope is fine to post it here, I'm newbie on github :-) Greetings


$ make
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../..                                                                     /dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-fini                                                                     te-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES                                                                      -c -o build/src/MPEToCV.cpp.o src/MPEToCV.cpp
src/MPEToCV.cpp: In member function 'void MPEToCV::pressNote(int)':
src/MPEToCV.cpp:73:54: error: no matching function for call to 'find(std::__cxx1                                                                     1::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
In file included from C:/msys64/mingw64/include/c++/7.2.0/bits/locale_facets.h:4                                                                     8:0,
                 from C:/msys64/mingw64/include/c++/7.2.0/bits/basic_ios.h:37,
                 from C:/msys64/mingw64/include/c++/7.2.0/ios:44,
                 from C:/msys64/mingw64/include/c++/7.2.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/7.2.0/iostream:39,
                 from ../../dep/include/rtmidi/RtMidi.h:59,
                 from ../../include/midi.hpp:11,
                 from src/MPEToCV.hpp:2,
                 from src/MPEToCV.cpp:1:
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note: candi                                                                     date: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_Ch                                                                     arT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istrea                                                                     mbuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note:   tem                                                                     plate argument deduction/substitution failed:
src/MPEToCV.cpp:73:54: note:   'std::_List_iterator<int>' is not derived from 's                                                                     td::istreambuf_iterator<_CharT>'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
src/MPEToCV.cpp: In member function 'void MPEToCV::releaseNote(int)':
src/MPEToCV.cpp:85:54: error: no matching function for call to 'find(std::__cxx1                                                                     1::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
In file included from C:/msys64/mingw64/include/c++/7.2.0/bits/locale_facets.h:4                                                                     8:0,
                 from C:/msys64/mingw64/include/c++/7.2.0/bits/basic_ios.h:37,
                 from C:/msys64/mingw64/include/c++/7.2.0/ios:44,
                 from C:/msys64/mingw64/include/c++/7.2.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/7.2.0/iostream:39,
                 from ../../dep/include/rtmidi/RtMidi.h:59,
                 from ../../include/midi.hpp:11,
                 from src/MPEToCV.hpp:2,
                 from src/MPEToCV.cpp:1:
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note: candi                                                                     date: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_Ch                                                                     arT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istrea                                                                     mbuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note:   tem                                                                     plate argument deduction/substitution failed:
src/MPEToCV.cpp:85:54: note:   'std::_List_iterator<int>' is not derived from 's                                                                     td::istreambuf_iterator<_CharT>'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
src/MPEToCV.cpp: In constructor 'MPEToCVWidget::MPEToCVWidget(MPEToCV*)':
src/MPEToCV.cpp:260:70: warning: 'TPort* rack::createOutput(rack::Vec, rack::Mod                                                                     ule*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-declarat                                                                     ions]
   addOutput(createOutput<PJ3410Port>(Vec(15 * 6, yPos - 5), module, i));
                                                                      ^
In file included from src/Erratic.hpp:1:0,
                 from src/MPEToCV.hpp:1,
                 from src/MPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
make: *** [../../compile.mk:62: build/src/MPEToCV.cpp.o] Error 1

**Comment by bafonso** [comment]
I believe I commented the offending code in the last v0.6 branch. Did you get the code from the v0.6 branch? Looks like the same error I was getting with linux.

**Comment by DCSIProductions** [comment]
I did "git clone" from the master page here
https://github.com/bafonso/Erratic
just few minutes before posting so I guess is the last one?

**Comment by bafonso** [comment]
You need to do "git checkout v0.6"

**Comment by DCSIProductions** [comment]
I'm not a programmer so I may got it wrong, however i cloned the Erratic, I entered in its directory and typed the command you said there and I got this results, hope it helps.

MINGW64 ~/rack/plugins/erratic
$ git checkout v0.6.0
Note: checking out 'v0.6.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b705740... Commented code breaking compiling on linux.

**Comment by bafonso** [comment]
Sorry it's "git checkout v0.6".

**Comment by DCSIProductions** [comment]
ok did, and right after I did again make dist but no, many warnings and still error, I will leave here below what it said but I have to go now so don't worry, just I hope it may be of use for you otherwise as said don't worry.
Talk later. cheers

$ git checkout v0.6
Previous HEAD position was b705740... Commented code breaking compiling on linux                                                                                                                .
Branch 'v0.6' set up to track remote branch 'v0.6' from 'origin'.
Switched to a new branch 'v0.6'

**(then I typed this)**

$ make dist
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../..                                                                                                                /dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-fini                                                                                                                te-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES                                                                                                                 -c -o build/src/MPEToCV.cpp.o src/MPEToCV.cpp
src/MPEToCV.cpp: In constructor 'MPEToCVWidget::MPEToCVWidget(MPEToCV*)':
src/MPEToCV.cpp:261:70: warning: 'TPort* rack::createOutput(rack::Vec, rack::Mod                                                                                                                ule*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-declarat                                                                                                                ions]
   addOutput(createOutput<PJ3410Port>(Vec(15 * 6, yPos - 5), module, i));
                                                                      ^
In file included from src/Erratic.hpp:1:0,
                 from src/MPEToCV.hpp:1,
                 from src/MPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
In file included from src/MPEToCV.cpp:1:0:
src/MPEToCV.hpp: In member function 'virtual void MPEMidiWidget::step()':
src/MPEToCV.hpp:333:17: warning: iteration 2 invokes undefined behavior [-Waggre                                                                                                                ssive-loop-optimizations]
    vSeparators[x]->box.pos.x = box.size.x / 4 * x;
    ~~~~~~~~~~~~~^
src/MPEToCV.hpp:332:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
src/MPEToCV.hpp: In member function 'void MPEMidiWidget::initialize(MPEToCV*)':
src/MPEToCV.hpp:309:17: warning: iteration 2 invokes undefined behavior [-Waggre                                                                                                                ssive-loop-optimizations]
    vSeparators[x]->box.size.y = midiChannelChoice->box.size.y;
    ~~~~~~~~~~~~~^
src/MPEToCV.hpp:308:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../..                                                                                                                /dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-fini                                                                                                                te-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES                                                                                                                 -c -o build/src/QuadMPEToCV.cpp.o src/QuadMPEToCV.cpp
src/QuadMPEToCV.cpp: In constructor 'QuadMPEToCVWidget::QuadMPEToCVWidget(QuadMP                                                                                                                EToCV*)':
src/QuadMPEToCV.cpp:50:76: warning: 'TPort* rack::createOutput(rack::Vec, rack::                                                                                                                Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-decla                                                                                                                rations]
   addOutput(createOutput<PJ3410Port>(Vec(2 * (40), yPos - 5), module, i * 4));
                                                                            ^
In file included from src/Erratic.hpp:1:0,
                 from src/QuadMPEToCV.hpp:2,
                 from src/QuadMPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/QuadMPEToCV.cpp:51:80: warning: 'TPort* rack::createOutput(rack::Vec, rack::                                                                                                                Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-decla                                                                                                                rations]
   addOutput(createOutput<PJ3410Port>(Vec(3 * (40), yPos - 5), module, i * 4 +                                                                                                                  ));
                                                                                                                                                                                                ^
In file included from src/Erratic.hpp:1:0,
                 from src/QuadMPEToCV.hpp:2,
                 from src/QuadMPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/QuadMPEToCV.cpp:52:80: warning: 'TPort* rack::createOutput(rack::Vec, rack::                                                                                                                Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-decla                                                                                                                rations]
   addOutput(createOutput<PJ3410Port>(Vec(4 * (40), yPos - 5), module, i * 4 +                                                                                                                  ));
                                                                                                                                                                                                ^
In file included from src/Erratic.hpp:1:0,
                 from src/QuadMPEToCV.hpp:2,
                 from src/QuadMPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/QuadMPEToCV.cpp:53:80: warning: 'TPort* rack::createOutput(rack::Vec, rack::                                                                                                                Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-decla                                                                                                                rations]
   addOutput(createOutput<PJ3410Port>(Vec(5 * (40), yPos - 5), module, i * 4 +                                                                                                                  ));
                                                                                                                                                                                                ^
In file included from src/Erratic.hpp:1:0,
                 from src/QuadMPEToCV.hpp:2,
                 from src/QuadMPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/QuadMPEToCV.cpp:57:72: warning: 'TPort* rack::createOutput(rack::Vec, rack::                                                                                                                Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-decla                                                                                                                rations]
  addOutput(createOutput<PJ3410Port>(Vec(2 * (40), yPos - 5), module, 20));
                                                                        ^
In file included from src/Erratic.hpp:1:0,
                 from src/QuadMPEToCV.hpp:2,
                 from src/QuadMPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
src/QuadMPEToCV.cpp:20:8: warning: unused variable 'labelHeight' [-Wunused-varia                                                                                                                ble]
  float labelHeight = 15;
        ^~~~~~~~~~~
In file included from src/QuadMPEToCV.cpp:1:0:
src/QuadMPEToCV.hpp: In member function 'virtual void QuadMPEMidiWidget::step()'                                                                                                                :
src/QuadMPEToCV.hpp:800:17: warning: iteration 2 invokes undefined behavior [-Wa                                                                                                                ggressive-loop-optimizations]
    vSeparators[x]->box.pos.x = box.size.x / 4 * x;
    ~~~~~~~~~~~~~^
src/QuadMPEToCV.hpp:799:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
src/QuadMPEToCV.hpp: In member function 'void QuadMPEMidiWidget::initialize(Quad                                                                                                                MPEToCV*)':
src/QuadMPEToCV.hpp:776:17: warning: iteration 2 invokes undefined behavior [-Wa                                                                                                                ggressive-loop-optimizations]
    vSeparators[x]->box.size.y = midiChannelChoice->box.size.y;
    ~~~~~~~~~~~~~^
src/QuadMPEToCV.hpp:775:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../..                                                                                                                /dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-fini                                                                                                                te-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES                                                                                                                 -c -o build/src/MPEBaseWidget.cpp.o src/MPEBaseWidget.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../..                                                                                                                /dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-fini                                                                                                                te-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES                                                                                                                 -c -o build/src/Erratic.cpp.o src/Erratic.cpp
g++ -o plugin.dll build/src/MPEToCV.cpp.o build/src/QuadMPEToCV.cpp.o build/src/                                                                                                                MPEBaseWidget.cpp.o build/src/Erratic.cpp.o  -L"../../dep/lib" -lrtmidi -shared                                                                                                                 -L../.. -lRack
build/src/MPEToCV.cpp.o: In function `MPEToCV::processMessage(rack::MidiMessage)                                                                                                                ':
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:123: undefined refere                                                                                                                nce to `MPEToCV::pressNote(int)'
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:118: undefined refere                                                                                                                nce to `MPEToCV::releaseNote(int)'
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:169: undefined refere                                                                                                                nce to `MPEToCV::releaseNote(int)'
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:118: undefined refere                                                                                                                nce to `MPEToCV::releaseNote(int)'
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:123: undefined refere                                                                                                                nce to `MPEToCV::pressNote(int)'
C:\msys64\home\Utente\rack\plugins\erratic/src/MPEToCV.cpp:169: undefined refere                                                                                                                nce to `MPEToCV::releaseNote(int)'
collect2.exe: error: ld returned 1 exit status
make: *** [../../compile.mk:52: plugin.dll] Error 1

**Comment by bafonso** [comment]
Ok maybe I will need to setup a windows box to make sure it compiles on
it...  I quickly commented some code but seems like it was expected to be
there :) not all compilers are alike...

**Comment by dizzisound** [comment]
@bafonso Hi, I pushed in this forked repo the version that worked for my Windows environment: 
https://github.com/dizzisound/Erratic/tree/v0.6

In short, this is what I committed in the forked repo:
- updated the few remaining `createOutput `calls;
- revised the termination conditions in the for loops involving LedDisplaySeparator* types, that are causing a segfault at runtime;
- for compile time errors in the Window build, I had to restore the `pressNote`/`releaseNote `members and a <algorithm> library inclusion in the `MPEBaseWidget.cpp` sourcefile;
- also a little edit in Makefile, but this is just a subtlety;
- matched the most recent Slug & Version definitions.

I don't know if you had some more issues in your Mac/Linux build, before committing the commented code, or if it's just the case that I forked a _in-progress_ commit.
Anyway, best wishes for the release, I hope you'll soon be able to submit your modules for the Plugin Manager inclusion!

**Comment by bafonso** [comment]
Hey @dizzisound , I incorporated most of the edits. I think the slug match... and version is 0.6.1 now with some changes I made. Surprisingly I never got erros with those loops(!)... I made a new 0.6.1 release replacing the old one.

**Comment by DCSIProductions** [comment]
Hi, ok I now compiled for windows using this link as source:
https://github.com/bafonso/Erratic/archive/0.6.1.zip
I got some warnings but I succeeded in making the win build.
here's the messages if it may be useful again :-)
Greets

-----

$ make dist
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MPEToCV.cpp.o src/MPEToCV.cpp
In file included from src/MPEToCV.cpp:1:0:
src/MPEToCV.hpp: In member function 'virtual void MPEMidiWidget::step()':
src/MPEToCV.hpp:333:17: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
    vSeparators[x]->box.pos.x = box.size.x / 4 * x;
    ~~~~~~~~~~~~~^
src/MPEToCV.hpp:332:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
src/MPEToCV.hpp: In member function 'void MPEMidiWidget::initialize(MPEToCV*)':
src/MPEToCV.hpp:309:17: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
    vSeparators[x]->box.size.y = midiChannelChoice->box.size.y;
    ~~~~~~~~~~~~~^
src/MPEToCV.hpp:308:21: note: within this loop
   for (int x = 1; x < 4; x++) {
                   ~~^~~
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/QuadMPEToCV.cpp.o src/QuadMPEToCV.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MPEBaseWidget.cpp.o src/MPEBaseWidget.cpp
g++  -Wsuggest-override -std=c++11  -DSLUG=ErraticInstruments -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Erratic.cpp.o src/Erratic.cpp
g++ -o plugin.dll build/src/MPEToCV.cpp.o build/src/QuadMPEToCV.cpp.o build/src/MPEBaseWidget.cpp.o build/src/Erratic.cpp.o  -L../../dep/lib -lrtmidi -shared -L../.. -lRack
rm -rf dist
mkdir -p dist/ErraticInstruments
# Strip and copy plugin binary
cp plugin.dll dist/ErraticInstruments/
strip -s dist/ErraticInstruments/plugin.dll
# Copy distributables
cp -R LICENSE.txt res dist/ErraticInstruments/
# Create ZIP package
cd dist && zip -5 -r ErraticInstruments-0.6.1-win.zip ErraticInstruments
  adding: ErraticInstruments/ (stored 0%)
  adding: ErraticInstruments/LICENSE.txt (deflated 60%)
  adding: ErraticInstruments/plugin.dll (deflated 74%)
  adding: ErraticInstruments/res/ (stored 0%)
  adding: ErraticInstruments/res/MyModule.svg (deflated 76%)
  adding: ErraticInstruments/res/QuadMPE.svg (deflated 84%)

**Comment by DCSIProductions** [comment]
ok after putting the plugins in the folder: Quad MPE to CV loads, while MPE to CV crashes the rack...

**Comment by dizzisound** [comment]
Yes, the loop thing is funny, I could compile but the plugin crashed on load, some backtrace pointed the iteration, so I simply tried out a fix, staying with the hardcoding for simplicity and performance. I am really glad you finalized your work, it's a really nice plugin and looks like an extension to the Core stuff to me. Best!

**Comment by dizzisound** [comment]
@DCSIProductions It looks like the last archive is missing the last-last fix to the iteration code through vSeparators in MPEToCV.cpp 
It could be that Bruno still has to drop the final binaries into the releases folder. Ciao!

**Comment by dizzisound** [comment]
Mmmh, sorry, the file to mention was MPEToCV.hpp. I am losing my header after 6 p.m. :-D

**Comment by bafonso** [comment]
Ok, I think I realized what was the mistake. I've made the changes and made a new 0.6.1 tag with these changes, can you please tell me if it still causes mistake? line 332 is now:
```
		for (int x = 0; x < 3; x++) {
			vSeparators[x]->box.pos.x = box.size.x / 4 * (x+1);
```
and 308 is now:
```		
for (int x = 0; x < 3; x++) {
   vSeparators[x] = Widget::create<LedDisplaySeparator>(pos);
   vSeparators[x]->box.size.y = midiChannelChoice->box.size.y;
   addChild(vSeparators[x]);
}
```

**Comment by DCSIProductions** [comment]
ok have git cloned from master and still an error, here's the whole stuff.

Utente@Probook-Pc MINGW64 ~/rack/plugins
$ git clone https://github.com/bafonso/Erratic.git
Cloning into 'Erratic'...
remote: Counting objects: 211, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 211 (delta 60), reused 61 (delta 25), pack-reused 108
Receiving objects: 100% (211/211), 736.43 KiB | 936.00 KiB/s, done.
Resolving deltas: 100% (109/109), done.

Utente@Probook-Pc MINGW64 ~/rack/plugins
$ cd erratic

Utente@Probook-Pc MINGW64 ~/rack/plugins/erratic
$ git submodule update --init --recursive

Utente@Probook-Pc MINGW64 ~/rack/plugins/erratic
$ make dist
g++  -Wsuggest-override -std=c++11  -DSLUG=Erratic -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/MPEToCV.cpp.o src/MPEToCV.cpp
src/MPEToCV.cpp: In member function 'void MPEToCV::pressNote(int)':
src/MPEToCV.cpp:73:54: error: no matching function for call to 'find(std::__cxx11::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
In file included from C:/msys64/mingw64/include/c++/7.2.0/bits/locale_facets.h:48:0,
                 from C:/msys64/mingw64/include/c++/7.2.0/bits/basic_ios.h:37,
                 from C:/msys64/mingw64/include/c++/7.2.0/ios:44,
                 from C:/msys64/mingw64/include/c++/7.2.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/7.2.0/iostream:39,
                 from ../../dep/include/rtmidi/RtMidi.h:59,
                 from ../../include/midi.hpp:11,
                 from src/MPEToCV.hpp:2,
                 from src/MPEToCV.cpp:1:
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MPEToCV.cpp:73:54: note:   'std::_List_iterator<int>' is not derived from 'std::istreambuf_iterator<_CharT>'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
src/MPEToCV.cpp: In member function 'void MPEToCV::releaseNote(int)':
src/MPEToCV.cpp:85:54: error: no matching function for call to 'find(std::__cxx11::list<int>::iterator, std::__cxx11::list<int>::iterator, int&)'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
In file included from C:/msys64/mingw64/include/c++/7.2.0/bits/locale_facets.h:48:0,
                 from C:/msys64/mingw64/include/c++/7.2.0/bits/basic_ios.h:37,
                 from C:/msys64/mingw64/include/c++/7.2.0/ios:44,
                 from C:/msys64/mingw64/include/c++/7.2.0/ostream:38,
                 from C:/msys64/mingw64/include/c++/7.2.0/iostream:39,
                 from ../../dep/include/rtmidi/RtMidi.h:59,
                 from ../../include/midi.hpp:11,
                 from src/MPEToCV.hpp:2,
                 from src/MPEToCV.cpp:1:
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note: candidate: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^~~~
C:/msys64/mingw64/include/c++/7.2.0/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
src/MPEToCV.cpp:85:54: note:   'std::_List_iterator<int>' is not derived from 'std::istreambuf_iterator<_CharT>'
  auto it = std::find(notes.begin(), notes.end(), note);
                                                      ^
src/MPEToCV.cpp: In constructor 'MPEToCVWidget::MPEToCVWidget(MPEToCV*)':
src/MPEToCV.cpp:260:70: warning: 'TPort* rack::createOutput(rack::Vec, rack::Module*, int) [with TPort = rack::PJ3410Port]' is deprecated [-Wdeprecated-declarations]
   addOutput(createOutput<PJ3410Port>(Vec(15 * 6, yPos - 5), module, i));
                                                                      ^
In file included from src/Erratic.hpp:1:0,
                 from src/MPEToCV.hpp:1,
                 from src/MPEToCV.cpp:1:
../../include/rack.hpp:72:19: note: declared here
 DEPRECATED TPort *createOutput(Vec pos, Module *module, int outputId) {
                   ^~~~~~~~~~~~
make: *** [../../compile.mk:62: build/src/MPEToCV.cpp.o] Error 1

**Comment by DCSIProductions** [comment]
sorry don't know why is making a line over certain lines here..

**Comment by DCSIProductions** [comment]
ok wait, if I git clone from the same pages of the 0.6 version it gives all the posted errors compiling, while if I download the zip itself and work on that, it builds fine, so now I succeeded building from this https://github.com/bafonso/Erratic/archive/v0.6.zip
and all worked fine

**Comment by DCSIProductions** [comment]
(see last post)
if you need it here's the win file.

**Comment by dizzisound** [comment]
@DCSIProduction Mmmh I'm not at my PC but it seems you forgot the `git checkout v0.6 `command before launching the "dist" task. I think the master branch could not be updated yet.

**Comment by DCSIProductions** [comment]
usually I follow
1) git clone (the stuff)
2) cd (into the new directory)
3) git submodule update --init --recursive
4) make dist

each time following these 4 steps I compile vcvrack plugins just fine...

**Comment by DCSIProductions** [comment]
I mean I never used git checkout, so who trained me forgot to tell me to do that :-) from now on I'll do. Thanks

**Comment by bafonso** [comment]
Ok, I will need to double check if the sources are not the same used to
compile. Yes u should do git clone --branch=v0.6 to get the right source
code.

**Comment by bafonso** [comment]
So the modules are working fine for you on windows, no crashes? If so I
will add this binary.

**Comment by DCSIProductions** [comment]
wait I'm doing it again using also checkout, I'm back in few minutes :)

**Comment by DCSIProductions** [comment]
ok all fine, here's the file you can take (I erased the one above)
And I followed
1) git clone https://github.com/bafonso/Erratic.git --branch=v0.6
2) cd erratic
3) git submodule update --init --recursive
4) git checkout v0.6
5) make dist
And all went fine :-)
Thanks for the heads up guys, I'm not a programmer so I'm learning stuff here with you :-)

[ErraticInstruments-0.6.1-win.zip](https://github.com/bafonso/Erratic/files/1881654/ErraticInstruments-0.6.1-win.zip)

**Comment by dizzisound** [comment]
Yes that's the regular and correct procedure, if the master branch is set as default and updated with the last commits/fixes. Inversely, if the new code, or the fixing code, is developed on a separate branch, it happens that this separate branch is "ahead" with regards to the code committed on the "official", master branch, until the updates are ported from the dev branch to the master branch. 
In the main Rack repository it happens something different, instead: the master branch is where all the code updates take place, and there are branch and tags that mantains the stable or released versions of the code. It's a bit complicated at first, but it's tremendously efficient for developing shared and versioned code. BTW,  the funny thing is that we still have to talk in English! Yet, it's more than a good rule for what concern coding work. I had to work on code written in Deutsch last week, you cannot think how I could figure out what variable names stood for! Paura! :-D

**Comment by DaveCasey** [comment]
Sorry for the slow reply. I was able to successfully load OS X binaries at https://github.com/bafonso/Erratic/releases/download/0.6.1/ErraticInstruments-0.6.1-mac.zip in Rack 0.6.

I was also able to build from source as of v0.6.1, so as far as I am concerned, all is happy. Thanks!!!
